### ISSUE TITLE
Skills Summit EOI

### ISSUE THREAD

**Issue by ragamouf** [au-research/skills-summit-2021#13]
@KathrynU asked for feedback on the summit EOI to send to last year's participants.

To kick off discussion, here are some thoughts:

1. The background is thorough, yet overwhelming. Can we cut it down, or maybe shift some content to a relevant question in the EOI?
1. Can we add a graphic that shows the draft program and how different days and events interact? I've added a very ugly jamboard screenshot.
1. Lots of these questions really depend on whether or not there is a lockdown in place, if I am vaccinated, how much the local community is vaxxed, whether a central hub venue is even appropriate. And during this current lockdown, my answers would be probably different (pessimistic, risk averse) to what I would answer out of lockdown (more optimistic and tolerant of risk). 
1. I would suggest to change all questions that start with “Are you interested” to “Do you intend?” To make each question and answer more definite.
1. I made some tweaks already to the 3rd last question, rephrasing to “How do you intend to participate in the 2021 eRAU conference”

[EOI copy has my suggestions here](https://docs.google.com/document/d/1I0DbjBESY47zl6VaU65moxGIBWvh27yJXXy8UsW_MNM/edit#)

**Comment by KathrynU** [comment]
Thanks @ragamouf . Very much appreciate your comments and the work you've done cutting through my verbosity.  I've created a gliffy image and added it to the google form, plus accepted all suggested changes.

**Comment by ragamouf** [comment]
Nice gliffy image @KathrynU!! I think it's just this para that needs finalising.

> We’re running the 2021 Skills Summit at eResearch AU to take advantage of our mutual audience.<insert stronger reasons here> This is your chance to participate in setting the national agenda for digital skills training in 2022.
