### ISSUE TITLE
Skills Summit day - Monday, Wednesday, Friday?

### ISSUE THREAD

**Issue by KathrynU** [au-research/skills-summit-2021#6]
Skills Summit day for active sessions will be in direct competition with other eRAU streams if run in parallel on that day.
Skills Summit dates/times that have minimal ‘competition’ with eRAU streams is a good idea. While Friday is always ‘risky’ due to conference fatigue; it may also be good as we’ll have input from the rest of the week (?)
Having the skills summit on the Monday might be a nice way to open the eRAU Conference?

**Comment by ragamouf** [comment]
Just before I chime in with "Monday's a great idea" I see in the Steering committee notes (2021-06-17) that the decision was made to stick with Wednesday. @KathrynU shall we close this issue?

**Comment by KathrynU** [comment]
Yes, Wednesday it is. I will close this issue.
